language: python
sudo: true
python:
  - "3.7"
before_script:
  - pip install -r requirements.txt
script: |
  chmod +x ./update_index.sh &&
  ./update_index.sh && 
  git status &&
  git add . && 
  git commit -m "update index.json" &&
  git push origin HEAD:master
