language: python
sudo: true
os:
  - linux
python:
  - "3.7"
before_script:
  - pip install -r requirements.txt
script: |
  python ./update_index.py && 
  git status &&
  git add . && 
  git commit -m "update index.json" &&
  git push origin HEAD:master
