language: python
python:
  - "3.7"
before_script:
  - pip install -r requirements.txt
script: |
  python ./update_index.py &&
  git add --all && 
  git commit -m "update index.json" &&
  git push https://${PAT}@github.com/Fazzani/epg.git HEAD:master
