language: python
python:
  - "3.7"
before_script: |
  pip install -r requirements.txt
  gem install gist &&
  (umask 0077 && echo $GIST_PAT > ~/.gist)
script: |
  python ./update_index.py
  gist -u $GIST_ID index_picons.json
